"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  dir: "ltr" | "rtl";
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Profile Page
    profileTitle: "User Profile",

         location: "Location",
    referenceNumber: "ID",
    accountDetails: "Account Details",
    accountStatus: "Account Status",
    fullName: "Full Name",
    emailAddress: "Email Address",
    department: "Department",
    phoneNumber: "Phone Number",
    memberSince: "Member since",
    lastLogin: "Last login",
    activeSession: "Active Session",
    edit: "Edit",
    logout: "Logout",
    language: "Language",
    english: "English",
    arabic: "Arabic",
    admin: "Admin",
    employee: "Employee",
    citizen: "Citizen",
    user: "User",
    operations: "Operations",
    // Titles & Sidebar
    agenciesTitle: "Agencies",
    complaintsTitle: "Complaints",
    dashboardTitle: "Dashboard",
    analyticsTitle: "Analytics",
    usersTitle: "Users",
    settingsTitle: "Settings",
    home: "Home",
    workflows: "Workflows",
    citizens: "Citizens",
    profile: "Profile",
    employees: "Employees",
    agencies: "Agencies",
    // Agencies Page
    addAgency: "Add Agency",
    editAgency: "Edit Agency",
    deleteAgency: "Delete Agency",
    agencyName: "Agency Name",
    logoUrl: "Logo URL",
    uploadLogo: "Upload Logo",
    actions: "Actions",
    searchAgencies: "Search agencies...",
    save: "Save",
    cancel: "Cancel",
    confirmDelete: "Are you sure you want to delete this agency?",
    noAgenciesFound: "No agencies found",
    getStartedAdding: "Get started by adding your first government agency.",
    clearSearch: "Clear Search",
    active: "Active",
    manageAgencies: "Manage Government Entities",
    clickToUpload: "Click or drag image to upload",
    failedToFetchAgencies: "Failed to fetch agencies",
    // Complaints
    complaints: "Complaints",
    addComplaint: "Add Complaint",
    searchComplaints: "Search complaints...",
    complaintSubject: "Subject",
    status: "Status",
    date: "Date",
    agency: "Agency",
    priority: "Priority",
    category: "Category",
    description: "Description",
    totalComplaints: "Total Complaints",
    pending: "Pending",
    inProgress: "In Progress",
    completed: "Completed",
    rejected: "Rejected",
    complaintsManagement: "Complaints Management",
    allAgencies: "All Agencies",
    complaintId: "Complaint ID",
    details: "Details",
     severity: "Severity",
    locationAndDate: "Location & Date",
    lock: "Lock",
    viewDetails: "View Details",
    locked: "Locked",
    lockedByMe: "By Me",
    urgent: "Urgent",
    high: "High",
    medium: "Medium",
    low: "Low",
    all: "All",
    noComplaintsFound: "No complaints found",
    adjustFilters: "Try adjusting your filters or search query",
    apps: "Apps",
    files: "Files",
    projects: "Projects",
    learn: "Learn",
    installApp: "Install App",
    newProject: "New Project",
    premium: "Premium",
    welcomeTitle: "Welcome to DesignAli Creative Suite",
    welcomeDesc: "Unleash your creativity with our comprehensive suite of professional design tools and resources.",
    explorePlans: "Explore Plans",
    takeTour: "Take a Tour",
    recentProjects: "Recent Projects",
    viewAll: "View All",
    progress: "Progress",
    due: "Due",
    members: "Members",
    recommendedForYou: "Recommended for You",
    design: "Design",
    illustration: "Illustration",
    recentActivity: "Recent Activity",
    viewAllActivity: "View all activity",
    storage: "Storage",
    usedSpace: "Used Space",
    images: "Images",
    videos: "Videos",
    upgradeStorage: "Upgrade Storage",
    allApplications: "All Applications",
    exploreManageTools: "Explore and manage your creative tools",
    allCategories: "All Categories",
    latestUpdates: "Latest Updates",
    new: "New",
    recent: "Recent",
    upToDate: "Up to date",
    openApp: "Open App",
    recentFiles: "Recent Files",
    grid: "Grid",
    list: "List",
    name: "Name",
    app: "App",
    modified: "Modified",
    size: "Size",
    shared: "Shared",
    private: "Private",
    allFiles: "All Files",
    sharedWithMe: "Shared with me",
    favorites: "Favorites",
    trash: "Trash",
    searchFiles: "Search files...",
    uploadFile: "Upload File",
    allProjects: "All Projects",
    activeProjects: "Active Projects",
    completedProjects: "Completed Projects",
    archivedProjects: "Archived Projects",
    searchProjects: "Search projects...",
    createNewProject: "Create New Project",
    learningCenter: "Learning Center",
    tutorials: "Tutorials",
    courses: "Courses",
    documentation: "Documentation",
    searchTutorials: "Search tutorials...",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    views: "views",
    instructor: "Instructor",
    manageProjectsDesc: "Manage and track your creative projects",
    learningCenterDesc: "Master your tools with professional tutorials",
    // App Descriptions
    pixelMasterDesc: "Advanced image editing and composition",
    vectorProDesc: "Professional vector graphics creation",
    videoStudioDesc: "Cinematic video editing and production",
    motionFXDesc: "Stunning visual effects and animations",
    pageCraftDesc: "Professional page design and layout",
    uxFlowDesc: "Intuitive user experience design",
    photoLabDesc: "Advanced photo editing and organization",
    docMasterDesc: "Document editing and management",
    webCanvasDesc: "Web design and development",
    threeDStudioDesc: "3D modeling and rendering",
    fontForgeDesc: "Typography and font creation",
    colorPaletteDesc: "Color scheme creation and management",
    // Categories
    creative: "Creative",
    video: "Video",
    photography: "Photography",
    document: "Document",
    web: "Web",
    threeD: "3D",
    typography: "Typography",
    // File Names & Times
    brandRedesign: "Brand Redesign.pxm",
    twoHoursAgo: "2 hours ago",
    companyLogo: "Company Logo.vec",
    yesterday: "Yesterday",
    productLaunchVideo: "Product Launch Video.vid",
    threeDaysAgo: "3 days ago",
    uiAnimation: "UI Animation.mfx",
    lastWeek: "Last week",
    magazineLayout: "Magazine Layout.pgc",
    twoWeeksAgo: "2 weeks ago",
    mobileAppDesign: "Mobile App Design.uxf",
    threeWeeksAgo: "3 weeks ago",
    productPhotography: "Product Photography.phl",
    lastMonth: "Last month",
    // Projects
    websiteRedesign: "Website Redesign",
    websiteRedesignDesc: "Complete overhaul of company website",
    mobileAppLaunch: "Mobile App Launch",
    mobileAppLaunchDesc: "Design and assets for new mobile application",
    brandIdentity: "Brand Identity",
    brandIdentityDesc: "New brand guidelines and assets",
    marketingCampaign: "Marketing Campaign",
    marketingCampaignDesc: "Summer promotion materials",
    // Tutorials
    digitalIllustrationMasterclass: "Mastering Digital Illustration",
    digitalIllustrationMasterclassDesc: "Learn advanced techniques for creating stunning digital art",
    uxDesignFundamentals: "UI/UX Design Fundamentals",
    uxDesignFundamentalsDesc: "Essential principles for creating intuitive user interfaces",
    videoEditingMasterclass: "Video Editing Masterclass",
    videoEditingMasterclassDesc: "Professional techniques for cinematic video editing",
    typographyEssentials: "Typography Essentials",
    typographyEssentialsDesc: "Create beautiful and effective typography for any project",
    colorTheoryForDesigners: "Color Theory for Designers",
    colorTheoryForDesignersDesc: "Understanding color relationships and psychology",
    totalCitizens: "Total Citizens",
    activeCitizens: "Active Citizens",
    verified: "Verified",
    unverified: "Unverified",
    registeredCitizens: "Registered Citizens",
    searchNameOrId: "Search name or id",
    citizenProfile: "Citizen Profile",
    verification: "Verification",
    contact: "Contact",
    viewProfile: "View Profile",
    deactivate: "Deactivate",
    activate: "Activate",
    deleteCitizen: "Delete Citizen",
    noCitizensFound: "No citizens found",
    citizensCriteriaDesc: "We couldn't find any citizens matching your current search criteria.",
    noPhone: "No phone",
    verifiedLabel: "Verified",
    pendingLabel: "Pending",
    activeLabel: "Active",
    inactiveLabel: "Inactive",
     totalEmployees: "Total Employees",
    activeEmployees: "Active Employees",
    inAgencies: "In Agencies",
    agencyEmployees: "Agency Employees",
     selectAgency: "Select Agency",
    addEmployee: "Add Employee",
    employeeMember: "Employee Member",
    
    deleteEmployee: "Delete Employee",
    noEmployeeFound: "No employee found",
    employeeCriteriaDesc: "We couldn't find any employees matching your current selection.",
    unknownAgency: "Unknown Agency",
  
    create: "Create",
    creating: "Creating...",
    // Employee-specific keys
    deleteEmployeeTitle: "Delete Employee Member",
    confirmDeletion: "Confirm Deletion",
    deleteConfirmationDesc: "Are you sure you want to permanently delete this employee? This action cannot be undone.",
    keepEmployee: "Keep Employee",
    deletePermanently: "Delete Permanently",
    employeeDetails: "Employee Details",
    internalIdentifier: "Internal Identifier",
    assignedAgency: "Assigned Agency",
    closeDetails: "Close Details",
    // Analytics Page
    monitorPerformance: "Monitor performance and gain insights into your workflows",
    last7Days: "Last 7 days",
    last30Days: "Last 30 days",
    last90Days: "Last 90 days",
    lastYear: "Last year",
    export: "Export",
    totalExecutions: "Total Executions",
    successRate: "Success Rate",
    thisMonth: "This month",
    perExecution: "Per execution",
    performance: "Performance",
    usagePatterns: "Usage Patterns",
    executionTrends: "Execution Trends",
    workflowExecutionsOverTime: "Workflow executions over time",
    successVsFailed: "Success vs Failed",
    executionOutcomesComparison: "Execution outcomes comparison",
    averageExecutionDuration: "Average Execution Duration",
    performanceTrendsOverTime: "Performance trends over time",
    workflowDistribution: "Workflow Distribution",
    executionBreakdownByWorkflowType: "Execution breakdown by workflow type",
    topPerformingWorkflows: "Top Performing Workflows",
    mostExecutedWorkflowsThisMonth: "Most executed workflows this month",
    runs: "runs",
    errorTypes: "Error Types",
    commonErrorCategories: "Most common error categories",
    errorTrends: "Error Trends",
    errorRateOverTime: "Error rate over time",
    systemOverview: "System Overview",
    realTimeAnalytics: "Real-time analytics and complaint statistics.",
    liveStatus: "Live Status",
    generateReport: "Generate Report",
    organizations: "Organizations",
    complaintsPerState: "Complaints per State",
    distributionAcrossGovernorates: "Distribution across governorates",
    complaintsPerAgency: "Complaints per Agency",
    categoricalBreakdown: "Categorical breakdown",
    complaintsByType: "Complaints by Type",
    breakdownByComplaintCategory: "Breakdown by complaint category",
    monthlyPerformanceTrend: "Monthly Performance Trend",
    statusWiseMonthlyBreakdown: "Status-wise monthly breakdown",
    // Analytics Additional
    errorAnalysis: "Error Analysis",
    success: "Success",
    failed: "Failed",
    productSync: "Product Sync",
    dataProcessing: "Data Processing",
    notifications: "Notifications",
    timeout: "Timeout",
    apiError: "API Error",
    dataValidation: "Data Validation",
    network: "Network",
    canceled: "Canceled",
    users: "Users",
    resources: "Resources",
    transportation: "Transportation",
    communication: "Communication",
    law: "Law",
    last6Months: "Last 6 Months",
    yearToDate: "Year to Date",
    errors: "Errors",
    jan: "Jan",
    feb: "Feb",
    mar: "Mar",
    apr: "Apr",
    may: "May",
    jun: "Jun",
    jul: "Jul",
    // Settings Page
    settings: "Settings",
    username: "Username",
    email: "Email",
    password: "Password",
    saveChanges: "Save Changes",
    usernamePlaceholder: "Enter your username",
    emailPlaceholder: "Enter your email",
    passwordPlaceholder: "Enter new password",
    loading: "Loading...",
    // Toast Messages & Additional Strings
     failedToLoadAgencies: "Failed to load agencies",
    failedToLoadEmployees: "Failed to load employees",
    fillRequiredFields: "Please fill in all required fields",
    employeeCreated: "Employee created successfully",
    failedToCreateEmployee: "Failed to create employee",
    employeeActivated: "Employee activated successfully",
    employeeDeactivated: "Employee deactivated successfully",
    failedToActivate: "Failed to activate employee",
    failedToDeactivate: "Failed to deactivate employee",
    citizenActivated: "Citizen activated successfully",
    citizenDeactivated: "Citizen deactivated successfully",
    failedToActivateCitizen: "Failed to activate citizen",
    failedToDeactivateCitizen: "Failed to deactivate citizen",
    agencyNameRequired: "Agency name is required",
    loginRequiredToCreate: "You must be logged in to create an agency",
    loginRequiredToUpdate: "You must be logged in to update an agency",
    agencyCreated: "Agency created successfully",
    failedToCreateAgency: "Failed to create agency",
    agencyUpdated: "Agency updated successfully",
    failedToUpdateAgency: "Failed to update agency",
    agencyDeleted: "Agency deleted successfully",
    failedToDeleteAgency: "Failed to delete agency",
    // Governorates
    damascus: "Damascus",
    ruralDamascus: "Rural Damascus",
    aleppo: "Aleppo",
    homs: "Homs",
    hama: "Hama",
    latakia: "Latakia",
    tartous: "Tartous",
    idlib: "Idlib",
    deirEzZor: "Deir ez-Zor",
    raqqa: "Raqqa",
    hasakah: "Hasakah",
    daraa: "Daraa",
    suwayda: "Suwayda",
    quneitra: "Quneitra",
    // Complaint Types
    serviceQuality: "Service Quality",
    corruption: "Corruption",
    delay: "Delay",
    misconduct: "Misconduct",
    otherType: "Other",
    // Complaints List
    complaintsList: "Complaints List",
    complaintID: "ID",
    complaintTitle: "Title",
    
    governorate: "Governorate",
    
    complaints_status: "Complaints Status",
    
     filterByStatus: "Filter by Status",
     pendingComplaints: "Pending",
    inProgressComplaints: "In Progress",
    completedComplaints: "Completed",
    rejectedComplaints: "Rejected",
     takeOwnership: "Take Ownership",
    releaseOwnership: "Release Ownership",
  },
  ar: {
    // Profile Page
    profileTitle: "ملف المستخدم",
        location: "الموقع",
    referenceNumber: "المعرف",

    accountDetails: "تفاصيل الحساب",
    accountStatus: "حالة الحساب",
    fullName: "الاسم الكامل",
    emailAddress: "البريد الإلكتروني",
    department: "القسم",
    phoneNumber: "رقم الهاتف",
    memberSince: "عضو منذ",
    lastLogin: "آخر تسجيل دخول",
    activeSession: "جلسة نشطة",
    edit: "تعديل",
    logout: "تسجيل الخروج",
    language: "اللغة",
    english: "الإنجليزية",
    arabic: "العربية",
    admin: "مسؤول",
    employee: "موظف",
    citizen: "مواطن",
    user: "مستخدم",
    operations: "العمليات",
    // Titles & Sidebar
    agenciesTitle: "الوكالات",
    complaintsTitle: "الشكاوى",
    dashboardTitle: "لوحة القيادة",
    analyticsTitle: "التحليلات",
    usersTitle: "المستخدمين",
    settingsTitle: "الإعدادات",
    home: "الرئيسية",
    workflows: "سير العمل",
    citizens: "المواطنون",
    profile: "الملف الشخصي",
    employees: "الموظفون",
    agencies: "الوكالات",
    // Agencies Page
    addAgency: "إضافة وكالة",
    editAgency: "تعديل الوكالة",
    deleteAgency: "حذف الوكالة",
    agencyName: "اسم الوكالة",
    logoUrl: "رابط الشعار",
    uploadLogo: "رفع الشعار",
    actions: "الإجراءات",
    searchAgencies: "البحث عن وكالات...",
    save: "حفظ",
    cancel: "إلغاء",
    confirmDelete: "هل أنت متأكد أنك تريد حذف هذه الوكالة؟",
    noAgenciesFound: "لم يتم العثور على وكالات",
    getStartedAdding: "ابدأ بإضافة أول وكالة حكومية لك.",
    clearSearch: "مسح البحث",
    active: "نشط",
    manageAgencies: "إدارة الكيانات الحكومية",
    clickToUpload: "انقر أو اسحب الصورة للرفع",
    failedToFetchAgencies: "فشل في جلب الوكالات",
    // Complaints
    complaints: "الشكاوى",
    addComplaint: "إضافة شكوى",
    searchComplaints: "البحث في الشكاوى...",
    complaintSubject: "الموضوع",
    status: "الحالة",
    date: "التاريخ",
    agency: "الوكالة",
    priority: "الأولوية",
    category: "الفئة",
    description: "الوصف",
    totalComplaints: "إجمالي الشكاوى",
    pending: "قيد الانتظار",
    inProgress: "قيد التنفيذ",
    completed: "مكتمل",
    rejected: "مرفوض",
    complaintsManagement: "إدارة الشكاوى",
    allAgencies: "جميع الوكالات",
    complaintId: "رقم الشكوى",
    details: "التفاصيل",
     severity: "الخطورة",
    locationAndDate: "الموقع والتاريخ",
    lock: "قفل",
    viewDetails: "عرض التفاصيل",
    locked: "مغلق",
    lockedByMe: "بواسطتي",
    urgent: "عاجل",
    high: "عالٍ",
    medium: "متوسط",
    low: "منخفض",
    all: "الكل",
    noComplaintsFound: "لم يتم العثور على شكاوى",
    adjustFilters: "حاول تعديل الفلاتر أو استعلام البحث",
    // Dashboard / Admin Page
     apps: "التطبيقات",
    files: "الملفات",
    projects: "المشاريع",
    learn: "تعلم",
    installApp: "تثبيت تطبيق",
    newProject: "مشروع جديد",
    premium: "مميز",
    welcomeTitle: "مرحباً بكم في مجموعة ديزاين علي الإبداعية",
    welcomeDesc: "أطلق العنان لإبداعك مع مجموعتنا الشاملة من أدوات وموارد التصميم الاحترافية.",
    explorePlans: "استكشاف الخطط",
    takeTour: "قم بجولة",
    recentProjects: "المشاريع الأخيرة",
    viewAll: "عرض الكل",
    progress: "التقدم",
    due: "تاريخ الاستحقاق",
    members: "الأعضاء",
    recommendedForYou: "موصى به لك",
    design: "تصميم",
    illustration: "رسوم توضيحية",
    recentActivity: "النشاط الأخير",
    viewAllActivity: "عرض كل النشاط",
    storage: "التخزين",
    usedSpace: "المساحة المستخدمة",
    images: "الصور",
    videos: "الفيديوهات",
    upgradeStorage: "ترقية التخزين",
    allApplications: "جميع التطبيقات",
    exploreManageTools: "استكشف وأدواتك الإبداعية وأدرها",
    allCategories: "جميع الفئات",
    latestUpdates: "آخر التحديثات",
    new: "جديد",
    recent: "حديث",
    upToDate: "محدث",
    openApp: "فتح التطبيق",
    recentFiles: "الملفات الأخيرة",
    grid: "شبكة",
    list: "قائمة",
    name: "الاسم",
    app: "التطبيق",
    modified: "معدل",
    size: "الحجم",
    shared: "مشترك",
    private: "خاص",
    allFiles: "جميع الملفات",
    sharedWithMe: "مشترك معي",
    favorites: "المفضلة",
    trash: "سلة المهملات",
    searchFiles: "البحث في الملفات...",
    uploadFile: "رفع ملف",
    allProjects: "جميع المشاريع",
    activeProjects: "المشاريع النشطة",
    completedProjects: "المشاريع المكتملة",
    archivedProjects: "المشاريع المؤرشفة",
    searchProjects: "البحث في المشاريع...",
    createNewProject: "إنشاء مشروع جديد",
    learningCenter: "مركز التعلم",
    tutorials: "الدروس التعليمية",
    courses: "الدورات",
    documentation: "التوثيق",
    searchTutorials: "البحث في الدروس...",
    beginner: "مبتدئ",
    intermediate: "متوسط",
    advanced: "متقدم",
    views: "مشاهدة",
    instructor: "المدرب",
    manageProjectsDesc: "إدارة وتتبع مشاريعك الإبداعية",
    learningCenterDesc: "أتقن أدواتك مع دروس تعليمية احترافية",
    // App Descriptions
    pixelMasterDesc: "تعديل وتكوين صور متقدم",
    vectorProDesc: "إنشاء رسومات متجهة احترافية",
    videoStudioDesc: "تحرير وإنتاج فيديو سينمائي",
    motionFXDesc: "تأثيرات بصرية ورسوم متحركة مذهلة",
    pageCraftDesc: "تصميم وتخطيط صفحات احترافي",
    uxFlowDesc: "تصميم تجربة مستخدم بديهية",
    photoLabDesc: "تحرير وتنظيم صور متقدم",
    docMasterDesc: "تحرير وإدارة المستندات",
    webCanvasDesc: "تصميم وتطوير المواقع",
    threeDStudioDesc: "نمذجة ورندر ثلاثي الأبعاد",
    fontForgeDesc: "إنشاء الخطوط والطباعة",
    colorPaletteDesc: "إنشاء وإدارة مخططات الألوان",
    // Categories
    creative: "إبداعي",
    video: "فيديو",
    photography: "تصوير",
    document: "مستند",
    web: "ويب",
    threeD: "ثلاثي الأبعاد",
    typography: "خطوط",
    // File Names & Times
    brandRedesign: "إعادة تصميم العلامة التجارية.pxm",
    twoHoursAgo: "قبل ساعتين",
    companyLogo: "شعار الشركة.vec",
    yesterday: "أمس",
    productLaunchVideo: "فيديو إطلاق المنتج.vid",
    threeDaysAgo: "قبل 3 أيام",
    uiAnimation: "تحريك واجهة المستخدم.mfx",
    lastWeek: "الأسبوع الماضي",
    magazineLayout: "تخطيط المجلة.pgc",
    twoWeeksAgo: "قبل أسبوعين",
    mobileAppDesign: "تصميم تطبيق الجوال.uxf",
    threeWeeksAgo: "قبل 3 أسابيع",
    productPhotography: "تصوير المنتج.phl",
    lastMonth: "الشهر الماضي",
    // Projects
    websiteRedesign: "إعادة تصميم الموقع",
    websiteRedesignDesc: "تجديد كامل لموقع الشركة",
    mobileAppLaunch: "إطلاق تطبيق الجوال",
    mobileAppLaunchDesc: "تصميم وأصول لتطبيق الجوال الجديد",
    brandIdentity: "هوية العلامة التجارية",
    brandIdentityDesc: "إرشادات وأصول العلامة التجارية الجديدة",
    marketingCampaign: "حملة تسويقية",
    marketingCampaignDesc: "مواد ترويجية للصيف",
    // Tutorials
    digitalIllustrationMasterclass: "إتقان الرسوم الرقمية",
    digitalIllustrationMasterclassDesc: "تعلم تقنيات متقدمة لإنشاء فن رقمي مذهل",
    uxDesignFundamentals: "أساسيات تصميم واجهة وتجربة المستخدم",
    uxDesignFundamentalsDesc: "مبادئ أساسية لإنشاء واجهات مستخدم بديهية",
    videoEditingMasterclass: "دورة تحرير الفيديو الاحترافية",
    videoEditingMasterclassDesc: "تقنيات احترافية لتحرير الفيديو السينمائي",
    typographyEssentials: "أساسيات فن الخط",
    typographyEssentialsDesc: "إنشاء خطوط جميلة وفعالة لأي مشروع",
    colorTheoryForDesigners: "نظرية الألوان للمصممين",
    colorTheoryForDesignersDesc: "فهم علاقات الألوان وعلم النفس",
    totalCitizens: "إجمالي المواطنين",
    activeCitizens: "المواطنون النشطون",
    verified: "موثق",
    unverified: "غير موثق",
    registeredCitizens: "المواطنون المسجلون",
    searchNameOrId: "البحث بالاسم أو الرقم التعريفي",
    citizenProfile: "ملف المواطن",
    verification: "التوثيق",
    contact: "الاتصال",
    viewProfile: "عرض الملف الشخصي",
    deactivate: "إلغاء التنشيط",
    activate: "تنشيط",
    deleteCitizen: "حذف المواطن",
    noCitizensFound: "لم يتم العثور على مواطنين",
    citizensCriteriaDesc: "لم نتمكن من العثور على أي مواطنين يطابقون معايير البحث الحالية.",
    noPhone: "لا يوجد هاتف",
    verifiedLabel: "موثق",
    pendingLabel: "قيد الانتظار",
    activeLabel: "نشط",
    inactiveLabel: "غير نشط",
     totalEmployees: "إجمالي الموظفين",
    activeEmployees: "الموظفون النشطون",
    inAgencies: "في الجهات",
    agencyEmployees: "موظفو الجهة",
     selectAgency: "اختر الجهة",
    addEmployee: "إضافة موظف",
    employeeMember: "عضو الموظفين",
 
    deleteEmployee: "حذف الموظف",
    noEmployeeFound: "لم يتم العثور على موظفين",
    employeeCriteriaDesc: "لم نتمكن من العثور على أي موظفين يطابقون اختيارك الحالي.",
    unknownAgency: "جهة غير معروفة",
    
    create: "إنشاء",
    creating: "جاري الإنشاء...",
    // Employee-specific keys
    deleteEmployeeTitle: "حذف عضو الموظف",
    confirmDeletion: "تأكيد الحذف",
    deleteConfirmationDesc: "هل أنت متأكد أنك تريد حذف هذا الموظف نهائيًا؟ لا يمكن التراجع عن هذا الإجراء.",
    keepEmployee: "الاحتفاظ بالموظف",
    deletePermanently: "حذف نهائي",
    employeeDetails: "تفاصيل الموظف",
    internalIdentifier: "المعرف الداخلي",
    assignedAgency: "الجهة المعينة",
    closeDetails: "إغلاق التفاصيل",
    // Analytics Page
    monitorPerformance: "راقب الأداء واحصل على رؤى حول سير عملك",
    last7Days: "آخر 7 أيام",
    last30Days: "آخر 30 يومًا",
    last90Days: "آخر 90 يومًا",
    lastYear: "العام الماضي",
    export: "تصدير",
    totalExecutions: "إجمالي التنفيذات",
    successRate: "معدل النجاح",
    thisMonth: "هذا الشهر",
    perExecution: "لكل تنفيذ",
    performance: "الأداء",
    usagePatterns: "أنماط الاستخدام",
    executionTrends: "اتجاهات التنفيذ",
    workflowExecutionsOverTime: "تنفيذات سير العمل بمرور الوقت",
    successVsFailed: "الناجحة مقابل الفاشلة",
    executionOutcomesComparison: "مقارنة نتائج التنفيذ",
    averageExecutionDuration: "متوسط مدة التنفيذ",
    performanceTrendsOverTime: "اتجاهات الأداء بمرور الوقت",
    workflowDistribution: "توزيع سير العمل",
    executionBreakdownByWorkflowType: "تفصيل التنفيذ حسب نوع سير العمل",
    topPerformingWorkflows: "سير العمل الأعلى أداءً",
    mostExecutedWorkflowsThisMonth: "سير العمل الأكثر تنفيذاً هذا الشهر",
    runs: "عمليات تشغيل",
    errorTypes: "أنواع الأخطاء",
    commonErrorCategories: "فئات الأخطاء الأكثر شيوعاً",
    errorTrends: "اتجاهات الأخطاء",
    errorRateOverTime: "معدل الأخطاء بمرور الوقت",
    systemOverview: "نظرة عامة على النظام",
    realTimeAnalytics: "التحليلات في الوقت الفعلي وإحصائيات الشكاوى.",
    liveStatus: "الحالة المباشرة",
    generateReport: "إنشاء تقرير",
    organizations: "المنظمات",
    complaintsPerState: "الشكاوى حسب المحافظة",
    distributionAcrossGovernorates: "التوزيع عبر المحافظات",
    complaintsPerAgency: "الشكاوى حسب الجهة",
    categoricalBreakdown: "التفصيل الفئوي",
    complaintsByType: "الشكاوى حسب النوع",
    breakdownByComplaintCategory: "تصنيف حسب فئة الشكوى",
    monthlyPerformanceTrend: "اتجاه الأداء الشهري",
    statusWiseMonthlyBreakdown: "التفصيل الشهري حسب الحالة",
    // Analytics Additional
    errorAnalysis: "تحليل الأخطاء",
    success: "ناجح",
    failed: "فاشل",
    productSync: "مزامنة المنتجات",
    dataProcessing: "معالجة البيانات",
    notifications: "التنبيهات",
    timeout: "انتهاء المهلة",
    apiError: "خطأ في الواجهة البرمجية",
    dataValidation: "تحقق من البيانات",
    network: "الشبكة",
    canceled: "ملغى",
    users: "المستخدمين",
    resources: "الموارد",
    transportation: "النقل",
    communication: "الاتصالات",
    law: "القانون",
    last6Months: "آخر 6 أشهر",
    yearToDate: "منذ بداية العام",
    errors: "أخطاء",
    jan: "يناير",
    feb: "فبراير",
    mar: "مارس",
    apr: "أبريل",
    may: "مايو",
    jun: "يونيو",
    jul: "يوليو",
    // Settings Page
    settings: "الإعدادات",
    username: "اسم المستخدم",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    saveChanges: "حفظ التغييرات",
    usernamePlaceholder: "أدخل اسم المستخدم الخاص بك",
    emailPlaceholder: "أدخل بريدك الإلكتروني",
    passwordPlaceholder: "أدخل كلمة مرور جديدة",
    loading: "جاري التحميل...",
    // Toast Messages & Additional Strings
     failedToLoadAgencies: "فشل في تحميل الوكالات",
    failedToLoadEmployees: "فشل في تحميل الموظفين",
    fillRequiredFields: "يرجى ملء جميع الحقول المطلوبة",
    employeeCreated: "تم إنشاء الموظف بنجاح",
    failedToCreateEmployee: "فشل في إنشاء الموظف",
    employeeActivated: "تم تفعيل الموظف بنجاح",
    employeeDeactivated: "تم إلغاء تفعيل الموظف بنجاح",
    failedToActivate: "فشل في تفعيل الموظف",
    failedToDeactivate: "فشل في إلغاء تفعيل الموظف",
    citizenActivated: "تم تفعيل المواطن بنجاح",
    citizenDeactivated: "تم إلغاء تفعيل المواطن بنجاح",
    failedToActivateCitizen: "فشل في تفعيل المواطن",
    failedToDeactivateCitizen: "فشل في إلغاء تفعيل المواطن",
    agencyNameRequired: "اسم الوكالة مطلوب",
    loginRequiredToCreate: "يجب عليك تسجيل الدخول لإنشاء وكالة",
    loginRequiredToUpdate: "يجب عليك تسجيل الدخول لتحديث الوكالة",
    agencyCreated: "تم إنشاء الوكالة بنجاح",
    failedToCreateAgency: "فشل في إنشاء الوكالة",
    agencyUpdated: "تم تحديث الوكالة بنجاح",
    failedToUpdateAgency: "فشل في تحديث الوكالة",
    agencyDeleted: "تم حذف الوكالة بنجاح",
    failedToDeleteAgency: "فشل في حذف الوكالة",
    // Governorates
    damascus: "دمشق",
    ruralDamascus: "ريف دمشق",
    aleppo: "حلب",
    homs: "حمص",
    hama: "حماة",
    latakia: "اللاذقية",
    tartous: "طرطوس",
    idlib: "إدلب",
    deirEzZor: "دير الزور",
    raqqa: "الرقة",
    hasakah: "الحسكة",
    daraa: "درعا",
    suwayda: "السويداء",
    quneitra: "القنيطرة",
    // Complaint Types
    serviceQuality: "جودة الخدمة",
    corruption: "الفساد",
    delay: "التأخير",
    misconduct: "سوء السلوك",
    otherType: "أخرى",
    // Complaints List
    complaintsList: "قائمة الشكاوي",
    complaintID: "المعرف",
    complaintTitle: "العنوان",
 
    governorate: "المحافظة",
     
    complaints_status: "حالة الشكاوى",
 
    filterByStatus: "تصفية حسب الحالة",
     pendingComplaints: "المعلقة",
    inProgressComplaints: "قيد المعالجة",
    completedComplaints: "المكتملة",
    rejectedComplaints: "المرفوضة",
     takeOwnership: "استلام الطلب",
    releaseOwnership: "إلغاء الاستلام",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang && (savedLang === "en" || savedLang === "ar")) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, dir, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
